
- name: Copy MongoDB repo
  ansible.builtin.copy:
    src: mongodb.repo
    dest: /etc/yum.repos.d/mongodb.repo

- name: Installing MongoDB
  ansible.builtin.yum:
    name: mongodb-org
    state: latest

- name: replacing IP in conf file
  ansible.builtin.replace:
    path: /etc/mongod.conf
    regexp: '127.0.0.1'
    replace: '0.0.0.0'

- name: Starting mongodb service
  ansible.builtin.systemd:
    name: mongod
    state: restarted
    enabled: yes