- name: Installing Nginx
  ansible.builtin.yum:
    name: nginx
    state: latest

- name: Removing old content
  ansible.builtin.file:
    path: /usr/share/nginx/html
    state: absent

- name: Creating nginx dir
  ansible.builtin.file:
    path: /usr/share/nginx/html
    state: directory

- name: Downloading and unzip frontend content
  ansible.builtin.unarchive:
    src: https://roboshop-artifacts.s3.amazonaws.com/frontend.zip
    dest: /usr/share/nginx/html
    remote_src: yes

- name: Copying nginx conf file
  ansible.builtin.template:
    src: nginx.conf
    dest: /etc/nginx/nginx.conf

- name: Copying roboshop conf file
  ansible.builtin.template:
    src: roboshop.conf
    dest: /etc/nginx/default.d/roboshop.conf


- name: Starting Nginx service
  ansible.builtin.systemd:
    name: nginx
    state: restarted
    enabled: yes

- name: Load ELK
  ansible.builtin.import_role:
    name: ELK
    tasks_from: filebeat

- name: Load prometheus
  ansible.builtin.import_role:
    name: prometheus
    tasks_from: node-exporter
