- name: Installing maven
  ansible.builtin.yum:
    name: maven
    state: latest

- name: App pre-setup
  ansible.builtin.import_tasks:
    file: pre-app-setup.yml

#- name: Maven Packges
#  ansible.builtin.shell: mvn clean package ; mv target/{{ component }}-1.0.jar {{ component }}.jar
#  args:
#    chdir: /app

- name: Systemd
  ansible.builtin.import_tasks:
    file: systemd.yml

- name: mysql schema
  ansible.builtin.import_tasks:
    file: mysql-schema.yml