
#  echo -e "${color}SCHEMA LOADING${nocolor}"
#  mysql -h mysql-dev.devopsbjr.online -uroot -pRoboShop@1 < ${app_path}/schema/${component}.sql &>>${log_file}
#

- name: install MYSQL
  ansible.builtin.yum:
    name: mysql
    state: latest

- name: load schema
  ansible.builtin.shell: mysql -h mysql-dev.devopsbjr.online -uroot -pRoboShop@1 < /app/schema/{{ component }}.sql
