
- name: Configuring Nodejs repo
  ansible.builtin.shell: https://rpm.nodesource.com/setup_lts.x | bash

- name: Installing NodeJS
  ansible.builtin.yum:
    name: nodejs
    state: installed

- name: App Pre-requisites
  ansible.builtin.import_tasks:
    file: pre-app-setup.yml

- name: Installing Nodejs dependcies
  ansible.builtin.shell: npm install
  args:
    chdir: /app

- name: Download DocumentDB Pem file
  ansible.builtin.get_url:
    url: https://truststore.pki.rds.amazonaws.com/global/global-bundle.pem
    dest: /app/rds-combined-ca-bundle.pem

- name: systemd
  ansible.builtin.import_tasks:
    file: systemd.yml



