
- name: Adding roboshop user
  ansible.builtin.user:
    name: roboshop

- name: Removing old content
  ansible.builtin.file:
    path: /app
    state: absent

- name: Creating {{ component }} dir
  ansible.builtin.file:
    path: /app
    state: directory

#- name: Downloading and unzip {{ component }} content
#  ansible.builtin.unarchive:
#    src: https://roboshop-artifacts.s3.amazonaws.com/{{ component }}.zip
#    dest: /app
#    remote_src: yes

- name: Download and extract app content from nexus
  ansible.builtin.unarchive:
    src: http://{{ lookup('amazon.aws.aws_ssm', 'roboshop.nexus.username', region='us-east-1') }}:{{ lookup('amazon.aws.aws_ssm', 'roboshop.nexus.password', region='us-east-1') }}@172.31.19.157:8081/repository/{{component}}/{{component}}-{{app_version}}.zip
    dest: /app
    remote_src: yes