
- name: Adding roboshop user
  ansible.builtin.user:
    name: roboshop

- name: Removing old content
  ansible.builtin.file:
    path: /app
    state: absent

- name: Creating nginx dir
  ansible.builtin.file:
    path: /app
    state: directory

- name: Downloading and unzip frontend content
  ansible.builtin.unarchive:
    src: https://roboshop-artifacts.s3.amazonaws.com/${{ component }}.zip
    dest: /app
    remote_src: yes